name: Build on Deploy

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4
              
            - name: Install latest nightly
              uses: actions-rs/toolchain@v1 # This is an archived repo
              with:
                  toolchain: nightly

            - name: install wasm target
              run: rustup target add wasm32-unknown-unknown
            - name: install trunk
              run: cargo install --locked trunk
            - run: chmod +x build.sh
            - run: ./build.sh
